test:
	luvit tests/test-xxhash.lua
	luvit tests/test-text-format.lua
	luvit tests/test-nibs-decoder.lua
	luvit tests/test-nibs-encoder.lua
	luvit tests/test-nibs-utils.lua

# publish: test
# 	lit publish nibs.lua

