test: test-xxhash test-bytes test-lib test-text-format test-trie test-nibs-encoder test-nibs-reader test-nibs-utils

test-xxhash:
	luvit tests/test-xxhash.lua
test-bytes:
	luvit tests/test-bytes.lua
test-lib:
	luvit tests/test-lib.lua
test-text-format:
	luvit tests/test-text-format.lua
test-trie:
	luvit tests/test-trie.lua
test-nibs-encoder:
	luvit tests/test-nibs-encoder.lua
test-nibs-reader:
	luvit tests/test-nibs-decoder.lua
test-nibs-utils:
	luvit tests/test-nibs-utils.lua

# publish: test
# 	lit publish nibs.lua
